"""initial schema — users, predictions, ack_history, suppressions

Revision ID: 0001_initial
Revises:
Create Date: 2026-05-26

Hand-written initial migration. Future revisions will be
autogenerated. Mirrors `app/db/models.py` exactly — when you change a
model, run::

    alembic revision --autogenerate -m "what changed"

and review the diff before committing.
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001_initial"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # --- users ------------------------------------------------------------
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False, server_default="analyst"),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_users"),
        sa.UniqueConstraint("username", name="uq_users_username"),
        sa.CheckConstraint("role IN ('admin', 'analyst')", name="ck_users_role_valid"),
    )
    op.create_index("ix_users_username", "users", ["username"], unique=False)

    # --- predictions ------------------------------------------------------
    op.create_table(
        "predictions",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("flow_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column("source_ip", sa.String(length=64), nullable=False),
        sa.Column("destination_ip", sa.String(length=64), nullable=False),
        sa.Column("source_port", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("destination_port", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("protocol", sa.String(length=16), nullable=False, server_default="N/A"),
        sa.Column("packet_size", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("duration", sa.Float(), nullable=False, server_default="0"),
        sa.Column("prediction", sa.String(length=16), nullable=False, server_default="Normal"),
        sa.Column("attack_type", sa.String(length=64), nullable=True),
        sa.Column("family", sa.String(length=64), nullable=True),
        sa.Column("subtype", sa.String(length=64), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False, server_default="0"),
        sa.Column("severity", sa.String(length=16), nullable=True),
        sa.Column("stage1_p", sa.Float(), nullable=True),
        sa.Column("stage2_p", sa.Float(), nullable=True),
        sa.Column("stage3_p", sa.Float(), nullable=True),
        sa.Column("stage2_probs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("stage3_probs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("ml_features", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("mitre", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=True),
        sa.Column("model_version", sa.String(length=64), nullable=True),
        sa.Column("snort_msg", sa.Text(), nullable=True),
        sa.Column("snort_sid", sa.Integer(), nullable=True),
        sa.Column("snort_classtype", sa.String(length=64), nullable=True),
        sa.Column("snort_priority", sa.Integer(), nullable=True),
        sa.Column("ack_state", sa.String(length=16), nullable=False, server_default="new"),
        sa.Column("ack_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ack_note", sa.Text(), nullable=True),
        sa.Column("ack_by", sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_predictions"),
        sa.ForeignKeyConstraint(
            ["ack_by"], ["users.id"],
            name="fk_predictions_ack_by_users",
            ondelete="SET NULL",
        ),
        sa.CheckConstraint(
            "ack_state IN ('new', 'reviewed', 'escalated', 'dismissed')",
            name="ck_predictions_ack_state_valid",
        ),
    )
    op.create_index("ix_predictions_flow_timestamp", "predictions", ["flow_timestamp"])
    op.create_index("ix_predictions_first_seen_at", "predictions", ["first_seen_at"])
    op.create_index("ix_predictions_family", "predictions", ["family"])
    op.create_index("ix_predictions_source", "predictions", ["source"])
    op.create_index("ix_predictions_ack_state", "predictions", ["ack_state"])
    # Composite index for campaign grouping (GROUP BY src, dst, family).
    op.create_index(
        "ix_predictions_campaign", "predictions", ["source_ip", "destination_ip", "family"]
    )

    # --- ack_history ------------------------------------------------------
    op.create_table(
        "ack_history",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("prediction_id", sa.String(length=128), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("from_state", sa.String(length=16), nullable=False),
        sa.Column("to_state", sa.String(length=16), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "changed_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.PrimaryKeyConstraint("id", name="pk_ack_history"),
        sa.ForeignKeyConstraint(
            ["prediction_id"], ["predictions.id"],
            name="fk_ack_history_prediction_id_predictions",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"],
            name="fk_ack_history_user_id_users",
            ondelete="SET NULL",
        ),
    )
    op.create_index(
        "ix_ack_history_pred_changed", "ack_history", ["prediction_id", "changed_at"]
    )

    # --- suppressions -----------------------------------------------------
    op.create_table(
        "suppressions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("value", sa.String(length=256), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("hits", sa.BigInteger(), nullable=False, server_default="0"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column("created_by", sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_suppressions"),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"],
            name="fk_suppressions_created_by_users",
            ondelete="SET NULL",
        ),
        sa.CheckConstraint(
            "kind IN ('sid', 'src_ip', 'src_cidr', 'flow_key')",
            name="ck_suppressions_kind_valid",
        ),
    )
    op.create_index("ix_suppressions_kind", "suppressions", ["kind"])


def downgrade() -> None:
    op.drop_index("ix_suppressions_kind", table_name="suppressions")
    op.drop_table("suppressions")

    op.drop_index("ix_ack_history_pred_changed", table_name="ack_history")
    op.drop_table("ack_history")

    op.drop_index("ix_predictions_campaign", table_name="predictions")
    op.drop_index("ix_predictions_ack_state", table_name="predictions")
    op.drop_index("ix_predictions_source", table_name="predictions")
    op.drop_index("ix_predictions_family", table_name="predictions")
    op.drop_index("ix_predictions_first_seen_at", table_name="predictions")
    op.drop_index("ix_predictions_flow_timestamp", table_name="predictions")
    op.drop_table("predictions")

    op.drop_index("ix_users_username", table_name="users")
    op.drop_table("users")
